export const SYNC_TABLES = [
  'accounts',
  'profiles',
  'board_messages',
  'guest_top_scores',
  'transactions',
  'active_puzzles',
  'interaction_logs',
  'agent_badges',
  'agent_world_quests',
  'agent_world_quest_signals',
  'spectator_messages',
  'resident_traits',
  'agent_runtime',
  'relationships',
  'agent_memories',
  'agent_promises',
  'world_objects',
  'world_events',
  'world_clock',
  'agent_observations',
  'agent_hypotheses',
  'hypothesis_evidence',
  'hypothesis_revisions',
  'world_rumors',
  'messages',
  'wallet_links',
  'land_grids',
  'land_purchases'
];

export const TABLE_PK = {
  accounts: 'id',
  profiles: 'agent_id',
  board_messages: 'id',
  guest_top_scores: 'agent_id',
  transactions: 'id',
  active_puzzles: 'node_id',
  interaction_logs: 'id',
  agent_badges: ['agent_id', 'badge_id'],
  agent_world_quests: ['agent_id', 'quest_id'],
  agent_world_quest_signals: 'id',
  spectator_messages: 'id',
  resident_traits: 'agent_id',
  agent_runtime: 'agent_id',
  relationships: ['agent_id', 'target_id'],
  agent_memories: 'id',
  agent_promises: 'id',
  world_objects: 'id',
  world_events: 'id',
  world_clock: 'id',
  agent_observations: 'id',
  agent_hypotheses: 'id',
  hypothesis_evidence: ['hypothesis_id', 'evidence_id'],
  hypothesis_revisions: 'id',
  world_rumors: 'id',
  messages: 'message_id',
  wallet_links: ['agent_id', 'wallet_address'],
  land_grids: 'grid_id',
  land_purchases: 'id'
};
